CREATE SEQUENCE SUSER001 START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SSKILL001 START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SSAVEDOFFER001 START WITH 1000 INCREMENT BY 1;

CREATE TABLE USERS
(
    ID BIGINT DEFAULT NEXT VALUE FOR SUSER001 NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(120) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    YEARS_EXPERIENCE INT NOT NULL,
    CONSTRAINT IPKUSERS001 PRIMARY KEY (ID),
    CONSTRAINT UKUSERS001 UNIQUE (EMAIL)
);

CREATE TABLE SKILL
(
    ID BIGINT DEFAULT NEXT VALUE FOR SSKILL001 NOT NULL,
    CODE VARCHAR(120) NOT NULL,
    LIBELLE VARCHAR(120) NOT NULL,
    CONSTRAINT IPKSKILL001 PRIMARY KEY (ID),
    CONSTRAINT UKSKILL001 UNIQUE (CODE)
);

CREATE TABLE USER_SKILL
(
    USER_ID BIGINT NOT NULL,
    SKILL_ID BIGINT NOT NULL,
    CONSTRAINT IPKUSERSKILL001 PRIMARY KEY (USER_ID, SKILL_ID),
    CONSTRAINT FKUSERSKILL_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FKUSERSKILL_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL (ID)
);

CREATE TABLE SAVED_OFFER
(
    ID BIGINT DEFAULT NEXT VALUE FOR SSAVEDOFFER001 NOT NULL,
    USER_ID BIGINT NOT NULL,
    OFFER_ID VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT IPKSAVEDOFFER001 PRIMARY KEY (ID),
    CONSTRAINT FKSAVEDOFFER_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION, ZIP_CODE, YEARS_EXPERIENCE) VALUES (1, 'Abdelhamid', 'AIT TALEB', 'abdelhamid.ait-taleb@yahoo.fr', 'Aix-en-provence', '13100', 6);

INSERT INTO SKILL (ID, CODE, LIBELLE) VALUES (1, '109870', 'Java');
INSERT INTO SKILL (ID, CODE, LIBELLE) VALUES (2, '113274', 'Framework Spring');
INSERT INTO SKILL (ID, CODE, LIBELLE) VALUES (3, '404167', 'Gérer et maitriser des bases de données (SQL/NoSQL)');
INSERT INTO SKILL (ID, CODE, LIBELLE) VALUES (4, '403031', 'Docker');
INSERT INTO SKILL (ID, CODE, LIBELLE) VALUES (5, '404054', 'Maîtrise d''un outil de gestion de flux (Kafka, Flink…)');
INSERT INTO SKILL (ID, CODE, LIBELLE) VALUES (6, '403870', 'React.js');

INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 1);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 2);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 3);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 4);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 5);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 6);
