CREATE SEQUENCE SOFFRES001 MINVALUE 1 MAXVALUE 999999999 START WITH 1 INCREMENT BY 1;

CREATE TABLE OFFRES
(
    ID NUMBER(10) NOT NULL,
    DESCRIPTION TEXT,
    CONSTAINT IPKOFFRES001 PRIMARY KEY (ID)
)

INSERT INTO OFFRES (DESCRIPTION) VALUES ('une premiere offre de test');
INSERT INTO OFFRES (DESCRIPTION) VALUES ('une deuxieme offre de test');