CREATE SEQUENCE SOFFRES001 START WITH 1 INCREMENT BY 50;

CREATE TABLE OFFRES
(
    ID BIGINT DEFAULT NEXT VALUE FOR SOFFRES001 NOT NULL,
    DESCRIPTION VARCHAR(255),
    CONSTRAINT IPKOFFRES001 PRIMARY KEY (ID)
);

INSERT INTO OFFRES (DESCRIPTION) VALUES ('une premiere offre de test');
INSERT INTO OFFRES (DESCRIPTION) VALUES ('une deuxieme offre de test');
