
CREATE SEQUENCE SUSER001 START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SSKILL001 START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SSAVEDOFFER001 START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SMATCHING001 START WITH 1000 INCREMENT BY 1;

CREATE TABLE USERS
(
    ID BIGINT DEFAULT NEXT VALUE FOR SUSER001 NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(120) NOT NULL,
    YEARS_EXPERIENCE INT NOT NULL,
    CONSTRAINT IPKUSERS001 PRIMARY KEY (ID),
    CONSTRAINT UKUSERS001 UNIQUE (EMAIL)
);

CREATE TABLE SKILL
(
    ID BIGINT DEFAULT NEXT VALUE FOR SSKILL001 NOT NULL,
    NAME VARCHAR(120) NOT NULL,
    CONSTRAINT IPKSKILL001 PRIMARY KEY (ID),
    CONSTRAINT UKSKILL001 UNIQUE (NAME)
);

CREATE TABLE USER_SKILL
(
    USER_ID BIGINT NOT NULL,
    SKILL_ID BIGINT NOT NULL,
    CONSTRAINT IPKUSERSKILL001 PRIMARY KEY (USER_ID, SKILL_ID),
    CONSTRAINT FKUSERSKILL_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FKUSERSKILL_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL (ID)
);

CREATE TABLE SAVED_OFFER
(
    ID BIGINT DEFAULT NEXT VALUE FOR SSAVEDOFFER001 NOT NULL,
    USER_ID BIGINT NOT NULL,
    OFFER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT IPKSAVEDOFFER001 PRIMARY KEY (ID),
    CONSTRAINT FKSAVEDOFFER_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FKSAVEDOFFER_OFFER FOREIGN KEY (OFFER_ID) REFERENCES OFFRES (ID)
);

CREATE TABLE MATCHING
(
    ID BIGINT DEFAULT NEXT VALUE FOR SMATCHING001 NOT NULL,
    USER_ID BIGINT NOT NULL,
    OFFER_ID BIGINT NOT NULL,
    SCORE DECIMAL(5,2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT IPKMATCHING001 PRIMARY KEY (ID),
    CONSTRAINT FKMATCHING_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FKMATCHING_OFFER FOREIGN KEY (OFFER_ID) REFERENCES OFFRES (ID)
);

INSERT INTO OFFRES (DESCRIPTION) VALUES ('Senior Java / Spring Boot Developer - Paris');
INSERT INTO OFFRES (DESCRIPTION) VALUES ('Data Engineer - Lyon');
INSERT INTO OFFRES (DESCRIPTION) VALUES ('Frontend React Developer - Lille');

INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION, YEARS_EXPERIENCE) VALUES (1, 'Amina', 'Ben Youssef', 'amina.benyoussef@example.com', 'Paris', 6);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION, YEARS_EXPERIENCE) VALUES (2, 'Lucas', 'Bernard', 'lucas.bernard@example.com', 'Lyon', 4);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION, YEARS_EXPERIENCE) VALUES (3, 'Nadia', 'El Amrani', 'nadia.elamrani@example.com', 'Lille', 8);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, EMAIL, LOCATION, YEARS_EXPERIENCE) VALUES (4, 'Thomas', 'Petit', 'thomas.petit@example.com', 'Nantes', 2);

INSERT INTO SKILL (ID, NAME) VALUES (1, 'Java');
INSERT INTO SKILL (ID, NAME) VALUES (2, 'Spring Boot');
INSERT INTO SKILL (ID, NAME) VALUES (3, 'SQL');
INSERT INTO SKILL (ID, NAME) VALUES (4, 'Docker');
INSERT INTO SKILL (ID, NAME) VALUES (5, 'Kafka');
INSERT INTO SKILL (ID, NAME) VALUES (6, 'React');
INSERT INTO SKILL (ID, NAME) VALUES (7, 'AWS');

INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 1);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 2);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 3);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (1, 4);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (2, 1);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (2, 3);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (2, 5);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (2, 7);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (3, 6);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (3, 3);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (3, 4);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (4, 6);
INSERT INTO USER_SKILL (USER_ID, SKILL_ID) VALUES (4, 3);

INSERT INTO SAVED_OFFER (ID, USER_ID, OFFER_ID, CREATED_AT) VALUES (1, 1, 101, TIMESTAMP '2026-08-21 09:10:00');
INSERT INTO SAVED_OFFER (ID, USER_ID, OFFER_ID, CREATED_AT) VALUES (2, 2, 151, TIMESTAMP '2026-08-21 09:20:00');
INSERT INTO SAVED_OFFER (ID, USER_ID, OFFER_ID, CREATED_AT) VALUES (3, 3, 201, TIMESTAMP '2026-08-21 09:30:00');
INSERT INTO SAVED_OFFER (ID, USER_ID, OFFER_ID, CREATED_AT) VALUES (4, 4, 201, TIMESTAMP '2026-08-21 09:35:00');

INSERT INTO MATCHING (ID, USER_ID, OFFER_ID, SCORE, CREATED_AT) VALUES (1, 1, 101, 96.50, TIMESTAMP '2026-08-21 10:00:00');
INSERT INTO MATCHING (ID, USER_ID, OFFER_ID, SCORE, CREATED_AT) VALUES (2, 2, 151, 89.25, TIMESTAMP '2026-08-21 10:05:00');
INSERT INTO MATCHING (ID, USER_ID, OFFER_ID, SCORE, CREATED_AT) VALUES (3, 3, 201, 94.10, TIMESTAMP '2026-08-21 10:10:00');
INSERT INTO MATCHING (ID, USER_ID, OFFER_ID, SCORE, CREATED_AT) VALUES (4, 4, 201, 72.40, TIMESTAMP '2026-08-21 10:15:00');
